server:
  port: 8088
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/RUNOOB"
#    username: "root"
#    password: "123456"
#    dbcp2:
#      driver: "com.mysql.cj.jdbc.Driver"
mybatis:
  mapper-locations: classpath:mybatis/*.xml